# Generated by Django 4.2.9 on 2024-01-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('publicado_em', models.DateTimeField(verbose_name='date published')),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
