# Generated by Django 4.2.9 on 2024-01-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publicado_em']},
        ),
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.CharField(default='teste', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.TextField(default='tst'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='teste'),
            preserve_default=False,
        ),
    ]
