# Generated by Django 4.2.9 on 2024-02-01 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outraapp', '0002_alter_post_options_post_img_url_post_resumo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('conteudo', models.CharField(max_length=500)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='outraapp.post')),
            ],
            options={
                'ordering': ['-publicado_em'],
            },
        ),
    ]
