# Generated by Django 4.2.9 on 2024-02-01 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outraapp', '0003_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['publicado_em']},
        ),
    ]
