# Generated by Django 4.2.9 on 2024-02-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outraapp', '0004_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
